### PR TITLE
Work around latest api change, see #35

### PR DESCRIPTION
**Pull request by StrathCole**

### CODE REVIEW

**Comment by spenwall** [comment]
I wonder if changing api version to 5 instead of 5.2 like suggested here https://github.com/thomasmunduchira/myq-api/issues/35. Would avoid any further issues with future 5.* releases.

**Comment by StrathCole** [comment]
> I wonder if changing api version to 5 instead of 5.2, like suggested here #35, would avoid any further issues with future 5.* releases.

Afaik no. Was at 5 already at an earlier time.

**Comment by nsnyder** [comment]
Either 5 or 5.2 seem to work at present. @thomasmunduchira this PR should get things fixed (or at least closer to fixed) until we get a chance to implement the v6 API.

**Comment by nsnyder** [comment]
@StrathCole Thanks for this PR! I thought this was going to be broken until we could get V6 working again, so it'll be nice to have this running soon.

**Comment by thomasmunduchira** [comment]
Thanks @StrathCole for the contribution! Apologies for the late turnaround time, I had a hectic week.

I verified this patch with the current set of E2E tests. This should be good to go!

**Comment by thomasmunduchira** [comment]
Cut a new release. Thanks again for the contribution!

**Pull request merged**
